language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn run knex migrate:latest
  - yarn run knex seed:run
  - npm run build
  - npm test

on:
  branch: master
